### ISSUE TITLE
DoesNotExist at /cart/ Cart matching query does not exist

### ISSUE THREAD

**Issue by jamilnoyda** [jamilnoyda/onlineshop#5]
DoesNotExist: Cart matching query does not exist.
[27/Nov/2019 12:56:28] "GET /cart/ HTTP/1.1" 500 88506
Internal Server Error: /cart/
Traceback (most recent call last):
  File "/home/jamil/gridle_code/onlineshop/env/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/jamil/gridle_code/onlineshop/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/jamil/gridle_code/onlineshop/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jamil/gridle_code/onlineshop/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jamil/gridle_code/onlineshop/env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/jamil/gridle_code/onlineshop/cart/views.py", line 64, in cart_detail
    cart = Cart.objects.get(user=request.user)
  File "/home/jamil/gridle_code/onlineshop/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/jamil/gridle_code/onlineshop/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: Cart matching query does not exist.

**Comment by jamilnoyda** [comment]
fixed
